### ISSUE TITLE
Deserialization issue: MismatchedInputException, Bean not yet resolved 

### ISSUE THREAD

**Issue by detomarco** [FasterXML/jackson-databind#3964]
### Description
When I try to deserialize this object

```json
{
	"id": 1,
	"fruits": [{
		"id": 2,
		"tree": 1,
		"calories": [{
			"id": 3,
			"fruit": 2
		}]
	}]
}
```

I get this error 
```
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot resolve ObjectId forward reference using property 'tree' (of type demo.jackson.Fruit): Bean not yet resolved
 at [Source: (String)"{
              "id": 1,
              "fruits": [
                {
                  "id": 2,
                  "tree": 1,
                  "calories": [
                    {
                      "id": 3,
                      "fruit": 2
                    }
                  ]
                }
              ]
            }"; line: 15, column: 13] (through reference chain: demo.jackson.Fruit["tree"])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1482)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer$BeanReferring.handleResolvedForwardReference(BeanDeserializer.java:1090)
	at com.fasterxml.jackson.databind.deser.impl.ReadableObjectId.bindItem(ReadableObjectId.java:64)
	at com.fasterxml.jackson.databind.deser.impl.PropertyValueBuffer.handleIdValue(PropertyValueBuffer.java:251)
	at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:207)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:424)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1322)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:331)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeWithObjectId(BeanDeserializerBase.java:1288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:162)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4526)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3468)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3436)
	at demo.jackson.LocationJavaTest.lambda$jsonDeserializeTree$0(LocationJavaTest.java:51)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:55)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:37)
	at org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:3082)
	at demo.jackson.LocationJavaTest.jsonDeserializeTree(LocationJavaTest.java:50)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:57)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)

```

### Version information
Current version: v2.11.4
It works with v2.11.3

Release note v2.11.4: https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.11.4
Issue probably created by [#2944](https://github.com/FasterXML/jackson-databind/issues/2944)

### To Reproduce
Demo
[jackson_parsing.zip](https://github.com/FasterXML/jackson-databind/files/11646046/jackson_parsing.zip)

the project contains a unit test in order to reproduce the bug

## Other information
It might be related to https://github.com/FasterXML/jackson-databind/issues/2152 but it has been created 2 years before the version 2.11.4 has been released

**Comment by cowtowncoder** [comment]
I know there's link to full repro, but would it be possible to inline POJO class definition for target class?
It'd be bit more convenient to see if this can be reproduced.

**Comment by detomarco** [comment]
Sure, this are the pojo classes (kotlin)
```kotlin
@JsonIdentityInfo(
    generator = ObjectIdGenerators.PropertyGenerator::class,
    property = "id",
    scope = Tree::class,
)
data class Tree(
    val id: Int,
    var fruits: MutableList<Fruit> = mutableListOf(),
)

@JsonIdentityInfo(
    generator = ObjectIdGenerators.PropertyGenerator::class,
    property = "id",
    scope = Fruit::class,
)
data class Fruit(
    val id: Long,
    var calories: List<Calories> = emptyList(),
) {
    var tree: Tree? = null
}

@JsonIdentityInfo(
    generator = ObjectIdGenerators.PropertyGenerator::class,
    property = "id",
    scope = Calories::class,
)
data class Calories(
    val id: Int,
) {
    var fruit: Fruit? = null
}

````

and this is the json I'm trying to deserialize

```json
             {
                "id": 1,
                "fruits": [
                  {
                    "id": 2,
                    "tree": 1,
                    "calories": [
                      {
                        "id": 3,
                        "fruit": 2
                      }
                    ]
                  }
                ]
              }
```

**Comment by yawkat** [comment]
@detomarco does this still happen with 2.15? 2.11 is long out of support. Also, please try making a reproducer with java only instead of kotlin, to confirm whether this is an issue specific to the kotlin module

**Comment by detomarco** [comment]
yes, still happening with the latest version

**Comment by detomarco** [comment]
I will open the same issue in the kotlin module then. Thank you

**Comment by detomarco** [comment]
sure, I close this issue for now. Thank you for your support!!

**Comment by detomarco** [comment]
This is the issue I've open in the kotlin module
https://github.com/FasterXML/jackson-module-kotlin/issues/681

**Comment by cowtowncoder** [comment]
Ok. One of first things to change in test would be:

```
.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
```

since this setting invariably hides other issues. I also notice use of `@JsonBackReference` with `@JsonIdentityInfo` and am suspicious of these two working together (they are overlapping features).

From ref to 2.11.3/4, looking at release notes I agree that #2944 looks suspicious

Aside from that, WDYT @JooHyukKim ?

**Comment by JooHyukKim** [comment]
@detomarco Thanks for your time and efforts in discussing the kotlin-module issue. 🙏🏼

> @JooHyukKim, what do you think?

Hmmm... The provided JSON object itself or the combination of `@JsonBackReference` and `@JsonIdentityInfo` is not something very unusual.

Then I made a PR in #3983 to provide a simplified test version that anyone can jump in and work on. While working on it, I noticed an excessive use of the value "id" and interestingly, the test without `@JsonCreator` passes in #3983. 

So thinking futher on this, suspicions are..

1. it possible that the `@JsonCreator` mechanism consumes the JSON value of "id" before it reaches the `@JsonBackReference + @JsonIdentityInfo` mechanisms, @cowtowncoder? 
2. Or maybe just too many `"id"` defined?

**Comment by JooHyukKim** [comment]
> @JooHyukKim, what do you think?

Hmmm... The provided JSON object itself or the combination of `@JsonBackReference` and `@JsonIdentityInfo` is not something very unusual.

Then I made a PR in #3983 to provide a simplified test version that anyone can jump in and work on. While working on it, I noticed an excessive use of the value "id" and interestingly, the test without `@JsonCreator` passes in #3983. 

So thinking futher on this, suspicions are..

1. it possible that the `@JsonCreator` mechanism consumes the JSON value of "id" before it reaches the `@JsonBackReference + @JsonIdentityInfo` mechanisms, @cowtowncoder? 
2. Or maybe just too many `"id"` defined?

**Comment by cowtowncoder** [comment]
@JooHyukKim Combination of `@JsonCreator` (or rather use of constructor-passing) and `@JsonIdentityInfo` or `@JsonBackReference` is fundamentally challenging, because Object can only have identity after being constructed.
So there's a chance this could be potentially case that is unsupportable without major rewriting of Object Id handling -- or in some cyclic cases, if we had dependency between 2 Objects that require use of constructors, impossible to support.

But first things first; thank you for the test case, I merged it in.

**Comment by JooHyukKim** [comment]
May I suggest changing the issue title as...

     `@JsonCreator` combined with `@JsonIdentityInfo`(or `@JsonBackReference`) fails deserialization with `MismatchedInputException :  Bean not yet resolved`

.... this, @cowtowncoder ? For issue tracking, etc...

**Comment by detomarco** [comment]
Thank you so much for your investigations guys!!

Sorry but I'm a bit lost :D 

In my understanding the problem is the combination of several annotations.
But in my original Kotlin code I did not add any of them, so I assume the problem is again in the jackson-kotlin module which adds those annotations. Did I get it right?
In that case I will reopen the issue there again


> @JooHyukKim Combination of `@JsonCreator` (or rather use of constructor-passing) and `@JsonIdentityInfo` or `@JsonBackReference` is fundamentally challenging, because Object can only have identity after being constructed. So there's a chance this could be potentially case that is unsupportable without major rewriting of Object Id handling -- or in some cyclic cases, if we had dependency between 2 Objects that require use of constructors, impossible to support.
> 
> But first things first; thank you for the test case, I merged it in.

it's not really clear to me why could be impossible to support since it was working well till v2.11.3

**Comment by k163377** [comment]
There is nothing that `kotlin-module` can do to fix this problem.

The `kotlin-module` basically marks the constructor as `JsonCreator`.
This is because if you simply use the `data class`, there are no argumentless constructors or setters there (I recommend checking the decompiled results).
And `kotlin-module` does not do any processing related to `JsonIdentityInfo`.

**Comment by cowtowncoder** [comment]
@detomarco It is not clear if this can be fixed or not; is it a fundamental limitation, or something that could be fixed.

**Comment by yihtserns** [comment]
## Observation
Reverting #2958 will indeed make the issue go away.

## Workaround
Let `Tree` be created first before constructing `Tree.fruits`, by removing the latter from `Tree`'s main constructor:
```
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator::class, property = "id", scope = Tree::class)
data class Tree(val id: Int) {
    var fruits: MutableList<Fruit> = mutableListOf()
}

```

**Comment by cowtowncoder** [comment]
@yihtserns Presumable breaking #2944 again tho? But perhaps this would allow finding a better fix that'd work for both cases?

**Comment by yihtserns** [comment]
@cowtowncoder I'm not proposing to revert that, am just double-confirming @detomarco's suspicion. 😅

**Comment by cowtowncoder** [comment]
@yihtserns yeah did not mean to imply that, just sort of spelled out what I think is the case. But I think it's a valid question as to whether original change could be modified.

Overall this once again leads back to my suspicion that many problems are due to incorrect linkage between `CreatorProperty` and other (Setter/getter/field) `SettableBeanProperty`ies.

**Comment by detomarco** [comment]
@yihtserns thanks for your advice, the workaround worked.

However I would suggest to find a proper solution to this problem because it prevents proper use of data classes in Kotlin or records in java 14+, and can become a big problem once they are adopted more and more

**Comment by cowtowncoder** [comment]
Fixed for 3.1.0 via #5444.
